application: rideshare-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# - url: /notifications/check
#   script: notifications.py
#   login: admin
- url: /static
  static_dir: app/static
- url: /.*
  script: main.app
builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(statistics/.*)
- ^(unittests/.*)
- ^(webtests/.*)